
name: Node.js CI

on:
  push:
    branches:  
    - master
    - releases/*
  pull_request:
    branches:
    - master
    - releases/*

jobs:
  build:
    
    runs-on: ubuntu-latest # test on different OS (based on user): Linux, Window

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    #   env:
    #     CI: true

    # Set up Docker
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    # -
    #   name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     image: claredng/portfolio
    #     registry: docker.io
    #     # push: true
    #     # tags: user/app:latest
    
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: claredng/portfolio:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

      
